// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Task struct {
	ID          int32
	Title       string
	CompletedAt sql.NullTime
	Position    int32
	CreatedAt   time.Time
}
