// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	Token     string
	UserID    int32
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	ClientID  sql.NullString
}

type PendingSession struct {
	ClientID     string
	SessionValue string
	ExpiresAt    time.Time
}

type Task struct {
	ID          int32
	Title       string
	CompletedAt sql.NullTime
	Position    int32
	CreatedAt   time.Time
	UserID      int32
}

type User struct {
	ID        int32
	Email     string
	CreatedAt time.Time
}
