// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title)
VALUES ($1)
RETURNING id, title, completed, created_at
`

func (q *Queries) CreateTask(ctx context.Context, title string) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, completed, created_at FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTask = `-- name: ToggleTask :one
UPDATE tasks
SET completed = NOT completed
WHERE id = $1
RETURNING id, title, completed, created_at
`

func (q *Queries) ToggleTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRow(ctx, toggleTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}
