// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CompleteTask(ctx context.Context, id int32) (Task, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id int32) error
	GetMaxPosition(ctx context.Context) (int32, error)
	GetPrevCompletedDate(ctx context.Context, dollar_1 time.Time) (time.Time, error)
	ListActiveTasks(ctx context.Context) ([]Task, error)
	ListCompletedTasks(ctx context.Context) ([]Task, error)
	ListCompletedTasksForDate(ctx context.Context, dollar_1 time.Time) ([]Task, error)
	ListHistoricalCompletedTasks(ctx context.Context, arg ListHistoricalCompletedTasksParams) ([]Task, error)
	UncompleteTask(ctx context.Context, arg UncompleteTaskParams) (Task, error)
	UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error
}

var _ Querier = (*Queries)(nil)
