// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET completed_at = now()
WHERE id = $1
RETURNING id, title, completed_at, position, created_at, user_id
`

func (q *Queries) CompleteTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, completeTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompletedAt,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (token, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateAuthTokenParams struct {
	Token     string
	UserID    int32
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, position, user_id)
VALUES ($1, $2, $3)
RETURNING id, title, completed_at, position, created_at, user_id
`

type CreateTaskParams struct {
	Title    string
	Position int32
	UserID   int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Title, arg.Position, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompletedAt,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getMaxPosition = `-- name: GetMaxPosition :one
SELECT COALESCE(MAX(position), 0)::int FROM tasks WHERE completed_at IS NULL AND user_id = $1
`

func (q *Queries) GetMaxPosition(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxPosition, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (email) VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, created_at
`

func (q *Queries) GetOrCreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getPrevCompletedDate = `-- name: GetPrevCompletedDate :one
SELECT DATE_TRUNC('day', completed_at)::timestamp as day
FROM tasks
WHERE completed_at IS NOT NULL
  AND DATE_TRUNC('day', completed_at) < $1::timestamp
  AND user_id = $2
ORDER BY completed_at DESC
LIMIT 1
`

type GetPrevCompletedDateParams struct {
	Column1 time.Time
	UserID  int32
}

func (q *Queries) GetPrevCompletedDate(ctx context.Context, arg GetPrevCompletedDateParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getPrevCompletedDate, arg.Column1, arg.UserID)
	var day time.Time
	err := row.Scan(&day)
	return day, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getValidAuthToken = `-- name: GetValidAuthToken :one
SELECT token, user_id, expires_at, used_at FROM auth_tokens
WHERE token = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetValidAuthToken(ctx context.Context, token string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getValidAuthToken, token)
	var i AuthToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT id, title, completed_at, position, created_at, user_id FROM tasks
WHERE completed_at IS NULL AND user_id = $1
ORDER BY position ASC
`

func (q *Queries) ListActiveTasks(ctx context.Context, userID int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompletedAt,
			&i.Position,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedTasks = `-- name: ListCompletedTasks :many
SELECT id, title, completed_at, position, created_at, user_id FROM tasks
WHERE completed_at IS NOT NULL
  AND completed_at >= CURRENT_DATE
  AND completed_at < CURRENT_DATE + INTERVAL '1 day'
  AND user_id = $1
ORDER BY completed_at DESC
`

func (q *Queries) ListCompletedTasks(ctx context.Context, userID int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompletedAt,
			&i.Position,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedTasksForDate = `-- name: ListCompletedTasksForDate :many
SELECT id, title, completed_at, position, created_at, user_id FROM tasks
WHERE completed_at IS NOT NULL
  AND completed_at >= $1::timestamp
  AND completed_at < $1::timestamp + INTERVAL '1 day'
  AND user_id = $2
ORDER BY completed_at DESC
`

type ListCompletedTasksForDateParams struct {
	Column1 time.Time
	UserID  int32
}

func (q *Queries) ListCompletedTasksForDate(ctx context.Context, arg ListCompletedTasksForDateParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedTasksForDate, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompletedAt,
			&i.Position,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoricalCompletedTasks = `-- name: ListHistoricalCompletedTasks :many
SELECT id, title, completed_at, position, created_at, user_id FROM tasks
WHERE completed_at IS NOT NULL
  AND completed_at >= $1::timestamp
  AND completed_at < $2::timestamp
  AND user_id = $3
ORDER BY completed_at DESC
`

type ListHistoricalCompletedTasksParams struct {
	Column1 time.Time
	Column2 time.Time
	UserID  int32
}

func (q *Queries) ListHistoricalCompletedTasks(ctx context.Context, arg ListHistoricalCompletedTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listHistoricalCompletedTasks, arg.Column1, arg.Column2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompletedAt,
			&i.Position,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens SET used_at = now() WHERE token = $1
`

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markAuthTokenUsed, token)
	return err
}

const uncompleteTask = `-- name: UncompleteTask :one
UPDATE tasks
SET completed_at = NULL, position = $2
WHERE id = $1
RETURNING id, title, completed_at, position, created_at, user_id
`

type UncompleteTaskParams struct {
	ID       int32
	Position int32
}

func (q *Queries) UncompleteTask(ctx context.Context, arg UncompleteTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, uncompleteTask, arg.ID, arg.Position)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompletedAt,
		&i.Position,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET position = $2 WHERE id = $1
`

type UpdateTaskPositionParams struct {
	ID       int32
	Position int32
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPosition, arg.ID, arg.Position)
	return err
}
